Import host-installer-10.2.9.tar.gz

diff --git a/startup/S05ramdisk b/startup/S05ramdisk
--- a/startup/S05ramdisk
+++ b/startup/S05ramdisk
@@ -30,77 +30,58 @@ start()
         ;;
       make-ramdisk=*)
         src=${arg#make-ramdisk=}
-	[ -d /tmp/ramdisk ] && continue
-	copied=0
-	errors=0
+        [ -d /tmp/ramdisk ] && continue
+        copied=0
+        errors=0
         echo -n "Copying installation image from $src to ramdisk..."
 
-	# hang around a while for USB devices to settle
-	for n in `seq 1 5`; do
-	  [ -b $src ] && break
-	  sleep 5
-	done
-	if ! [ -b $src ]; then
-	    echo " failed"
-	    continue
-	fi
+        # hang around a while for USB devices to settle
+        for n in `seq 1 5`; do
+          [ -b $src ] && break
+          sleep 5
+        done
+        if ! [ -b $src ]; then
+            echo " failed"
+            continue
+        fi
 
-	# mount the source
-	mkdir /tmp/src
-	for fs in iso9660 vfat ext3; do
-	  mount -t $fs -o ro $src /tmp/src 2>/dev/null && break
-	done
-	if grep -q ' /tmp/src ' /proc/mounts; then 
+        # mount the source
+        mkdir /tmp/src
+        for fs in iso9660 vfat ext3; do
+          mount -t $fs -o ro $src /tmp/src 2>/dev/null && break
+        done
+        if grep -q ' /tmp/src ' /proc/mounts; then 
 
-	  # create appropriately sized ramdisk and populate
+          # create appropriately sized ramdisk and populate
           if [ -d /tmp/src/$xsinst ]; then
-	    # ISO mode, assume the ISOs unpack to less than 110% of the
-	    # ISO size. We'll also add 1000k headroom later.
-	    fssize=`du -ks /tmp/src/$xsinst | awk '{print $1}'`
+            # ISO mode, assume the ISOs unpack to less than 110% of the
+            # ISO size. We'll also add 1000k headroom later.
+            fssize=`du -ks /tmp/src/$xsinst | awk '{print $1}'`
           else
-	    # Original mode
-  	    fssize=`df -k /tmp/src | sed -ne 's#^/[^ ]\+ \+[0-9]\+ \+\([0-9]\+\).*#\1#p'`
-	  fi
-	  mkdir /tmp/ramdisk
-	  shopt -s dotglob
-	  mount -t tmpfs -o size=$((fssize * 11/10 + 2000))k tmpfs /tmp/ramdisk
+            # Original mode
+            fssize=`df -k /tmp/src | sed -ne 's#^/[^ ]\+ \+[0-9]\+ \+\([0-9]\+\).*#\1#p'`
+          fi
+          mkdir /tmp/ramdisk
+          shopt -s dotglob
+          mount -t tmpfs -o size=$((fssize * 11/10 + 2000))k tmpfs /tmp/ramdisk
           if [ -d /tmp/src/$xsinst ]; then
-	    # ISO mode. Iterate through ISOs in the $xsinst directory
-	    # unpacking each one to the ramdisk
+            # ISO mode. Iterate through ISOs in the $xsinst directory
+            # unpacking each one to the ramdisk
             for isofile in /tmp/src/$xsinst/*.iso; do
               if [ -f $isofile ]; then
+                basedir=$(basename $isofile .iso)
                 mkdir -p /tmp/srciso
-                mount -oloop -t iso9660 $isofile /tmp/srciso
-		if grep -q ' /tmp/srciso ' /proc/mounts; then
+                mount -oloop,ro -t iso9660 $isofile /tmp/srciso
+                if grep -q ' /tmp/srciso ' /proc/mounts; then
                   if [ -f /tmp/srciso/.treeinfo ]; then
                     # This is the main product ISO
                     if ! cp -a /tmp/srciso/* /tmp/ramdisk; then
-		      errors=$(($errors + 1))
+                      errors=$(($errors + 1))
                     fi
-                  fi
-                  if [ -f /tmp/srciso/XS-REPOSITORY-LIST ]; then
-                    # Additional repositories
-                    for repo in $(cat /tmp/srciso/XS-REPOSITORY-LIST); do
-                      if cp -a /tmp/srciso/$repo /tmp/ramdisk; then
-                        echo $repo >> /tmp/ramdisk/XS-REPOSITORY-LIST
-                      else
-			errors=$(($errors + 1))
-                      fi
-                    done
-                  fi
-                  if [ -f /tmp/srciso/XS-REPOSITORY -a -f /tmp/srciso/XS-PACKAGES ]; then
-                    # Supplemental pack
-                    orig=$(sed -ne '/<repository/ s/.*originator="\([^"]*\)".*/\1/p' /tmp/srciso/XS-REPOSITORY)
-                    name=$(sed -ne '/<repository/ s/.*name="\([^"]*\)".*/\1/p' /tmp/srciso/XS-REPOSITORY)
-		    packdir="$orig#$name"
-                    if [ -n "$packdir" ]; then
-                      mkdir -p /tmp/ramdisk/$packdir
-                      if cp -a /tmp/srciso/* /tmp/ramdisk/$packdir; then
-			echo $packdir >> /tmp/ramdisk/XS-REPOSITORY-LIST
-		      else
-                        errors=$(($errors + 1))
-		      fi
-                    else
+                  else
+                    # an update ISO
+                    mkdir -p /tmp/ramdisk/$basedir
+                    if ! cp -a /tmp/srciso/* /tmp/ramdisk/$basedir; then
                       errors=$(($errors + 1))
                     fi
                   fi
@@ -118,7 +99,7 @@ start()
                 continue
               fi
               if ! cp -a $f /tmp/ramdisk; then
-		errors=$(($errors + 1))
+                errors=$(($errors + 1))
               fi
             done
             if [ $errors -eq 0 ]; then
@@ -130,19 +111,19 @@ start()
               copied=1
             fi
           fi
-	  if [ $copied -eq 1 ] ; then
-	    echo " done"
-	  else
-	    umount /tmp/ramdisk
-	    rmdir /tmp/ramdisk
-	  fi
-	  umount /tmp/src
-	fi
-	rmdir /tmp/src
-	if [ $copied -eq 0 ]; then
-	  echo " failed"
-	  ret=1
-	fi;;
+          if [ $copied -eq 1 ] ; then
+            echo " done"
+          else
+            umount /tmp/ramdisk
+            rmdir /tmp/ramdisk
+          fi
+          umount /tmp/src
+        fi
+        rmdir /tmp/src
+        if [ $copied -eq 0 ]; then
+          echo " failed"
+          ret=1
+        fi;;
     esac
   done
   return $ret
